/**************************************************************************
 * C S 429 system emulator
 *
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>

#include "hw_elts.h"
#include "instr.h"
#include "instr_pipeline.h"

extern uint8_t D_src1, D_src2;

// LUT for extracting registers according to format.
extract_reg_func_t extract_regs_table[NUM_FORMATS];

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally.
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */
static comb_logic_t generate_DXMW_control(opcode_t op, d_ctl_sigs_t *D_sigs,
                                          x_ctl_sigs_t *X_sigs,
                                          m_ctl_sigs_t *M_sigs,
                                          w_ctl_sigs_t *W_sigs) {
    // Student TODO
    D_sigs->src2_sel = (op == OP_STUR);
    
    // check if using multipurpose val for adrp instead of vala
    X_sigs->vala_sel = (op == OP_ADRP);
    // check if using reg for valb (or for ret (b3))
    X_sigs->valb_sel = (op == OP_ADDS_RR || op == OP_SUBS_RR || op == OP_CMP_RR || 
                        op == OP_CMN_RR || op == OP_ORR_RR || op == OP_EOR_RR || 
                        op == OP_ANDS_RR || op == OP_TST_RR || op == OP_LSL_RR || 
                        op == OP_LSR_RR || op == OP_RET || op == OP_MVN); 
    // check if setting nzcv flags                   
    //X_sigs->set_flags = (op == OP_ADDS_RR || op == OP_SUBS_RR || op == OP_ANDS_RR);
    X_sigs->set_flags = (op == OP_ADDS_RR || op == OP_SUBS_RR || op == OP_ANDS_RR ||
                        op == OP_CMP_RR || op == OP_CMN_RR || op == OP_TST_RR);

    // mem signals
    M_sigs->dmem_read = (op == OP_LDUR);
    M_sigs->dmem_write = (op == OP_STUR);

    // check if writing to x30
    W_sigs->dst_sel = (op == OP_BL);
    // check if write val comes from mem
    W_sigs->wval_sel = (op == OP_LDUR);
    // enable write for any instr that modifies a reg
    W_sigs->w_enable = (op == OP_LDUR || op == OP_MOVZ || op == OP_MOVK || 
                        op == OP_ADRP || op == OP_ADD_RI || op == OP_ADDS_RR || 
                        op == OP_SUB_RI || op == OP_SUBS_RR || op == OP_ORR_RR || 
                        op == OP_EOR_RR || op == OP_ANDS_RR || op == OP_LSL_RI || 
                        op == OP_LSR_RI || op == OP_LSL_RR || op == OP_LSR_RR || 
                        op == OP_ASR || op == OP_BL || op == OP_MVN);
    return;
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format
 * instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */
static comb_logic_t extract_immval(uint32_t insnbits, opcode_t op,
                                   int64_t *imm) {
    // Student TODO
    switch (op)
    {
    // M
    case OP_LDUR:
    case OP_STUR:
        *imm = bitfield_s64(insnbits, 12, 9);
        break;
    // I1
    case OP_MOVK:
    case OP_MOVZ:
        *imm = bitfield_u32(insnbits, 5, 16);
        break;
    // I2
    case OP_ADRP:
        int64_t immhi = bitfield_s64(insnbits, 5, 19);
        uint64_t immlo = bitfield_u32(insnbits, 29, 2);
        // int64_t combined = (immhi << 2) | immlo;
        // combined = (combined << 43) >> 43;
        // *imm = combined << 12;
        *imm = ((immhi << 2) | (int64_t)immlo) << 12;
        break;
    // RI (arithmetic)
    case OP_ADD_RI:
    case OP_SUB_RI:
        *imm = bitfield_u32(insnbits, 10, 12);
        break;
    // RI (logical)
    
    case OP_ASR:
    case OP_LSR_RI:
        *imm = bitfield_u32(insnbits, 16, 6);
        break;
    case OP_LSL_RI:
        *imm = 63 - bitfield_u32(insnbits, 10, 6);
        break;
    default:
        *imm = 0;
        break;
    }
    return;
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    // Student TODO
    switch(op){
        case OP_ADD_RI:
        case OP_ADDS_RR:
        case OP_CMN_RR:
        // address calc
        case OP_LDUR:
        case OP_STUR:
            *ALU_op = PLUS_OP;
            break;
        
        case OP_SUB_RI:
        case OP_SUBS_RR:
        case OP_CMP_RR:
            *ALU_op = MINUS_OP;
            break;
        
        case OP_MVN:
            *ALU_op = INV_OP;
            break;
        
        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;
        case OP_MOVK:
            *ALU_op = MOVK_OP;
            break;
        
        case OP_ANDS_RR:
        case OP_TST_RR:
            *ALU_op = AND_OP;
            break;
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;
        
        case OP_LSL_RI:
        case OP_LSL_RR:
            *ALU_op = LSL_OP;
            break;
        case OP_LSR_RI:
        case OP_LSR_RR:
            *ALU_op = LSR_OP;
            break;
        case OP_ASR:
            *ALU_op = ASR_OP;
            break;
        
        default:
            *ALU_op = PASS_A_OP;
    }
    return;
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */
comb_logic_t copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    // Student TODO
    *dest = *src;
    return;
}

comb_logic_t copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    // Student TODO
    *dest = *src;
    return;
}

/*
 * Utility functions for extracting src1, src2, and dst registers.
 * STUDENT TO-DO:
 * Update fix_regs to determine whether 31 represents SP or XZR.
 */
comb_logic_t fix_regs(opcode_t op, uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    // Student TODO
    switch(op){
        case OP_CMN_RR:
        case OP_CMP_RR: 
        case OP_TST_RR:
            *dst = XZR_NUM;
            break;
        
        case OP_MVN:
            *src1 = XZR_NUM;
            break;
        
        case OP_LDUR:
        case OP_STUR:
        case OP_ADD_RI:
        case OP_SUB_RI:
            if (*src1 == 31) *src1 = SP_NUM;
            if (*dst == 31) *dst = SP_NUM;
            break;
        
        default:
            if (*src1 == 31) *src1 = XZR_NUM;
            if (*src2 == 31) *src2 = XZR_NUM;
            if (*dst == 31) *dst = XZR_NUM;
            break;
    }
    return;
}

/*
 * Extract src1, src2, and dst registers from instruction. Do not modify.
 */
comb_logic_t extract_regs(uint32_t insnbits, opcode_t op, format_t format,
                          uint8_t *src1, uint8_t *src2, uint8_t *dst) {
    extract_regs_table[format](insnbits, op, src1, src2, dst);
    fix_regs(op, src1, src2, dst);
    return;
}

/*
 * Pass through for FORMAT_ERROR. Do not modify.
 */
comb_logic_t format_other(uint32_t insnbits, opcode_t op, uint8_t *src1,
                          uint8_t *src2, uint8_t *dst) {
    return;
}

/*
 * Extract registers for each instruction format.
 * STUDENT TO-DO:
 * Fill out. Remember that some formats may not require any work.
 */
comb_logic_t format_m(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    // Student TODO
    *src1 = bitfield_u32(insnbits, 5, 5);
    if (op == OP_STUR) {
        *src2 = bitfield_u32(insnbits, 0, 5); // rt = data to store
    } else {
        *dst = bitfield_u32(insnbits, 0, 5); // rt = dest for load
    }
    return;
}

comb_logic_t format_i1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    *dst = bitfield_u32(insnbits, 0, 5);
    if (op == OP_MOVK) *src1 = *dst;
    return;
}

comb_logic_t format_i2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

comb_logic_t format_rr(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    *src1 = bitfield_u32(insnbits, 5, 5);
    *src2 = bitfield_u32(insnbits, 16, 5);
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

comb_logic_t format_ri(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    *src1 = bitfield_u32(insnbits, 5, 5);
    *dst = bitfield_u32(insnbits, 0, 5);
    return;
}

// uncond b
comb_logic_t format_b1(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    if (op == OP_BL) *dst = 30; // save ret address to x30
    return;
}

// cond b
comb_logic_t format_b2(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}

// ret
comb_logic_t format_b3(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    *src1 = bitfield_u32(insnbits, 5, 5); // rn = return address
    return;
}

/* For NOP/HLT instructions.
 */
comb_logic_t format_s(uint32_t insnbits, opcode_t op, uint8_t *src1,
                      uint8_t *src2, uint8_t *dst) {
    return;
}

#ifdef EC
/*
 * Extra credit instructions.
 */
comb_logic_t format_ec(uint32_t insnbits, opcode_t op, uint8_t *src1,
                       uint8_t *src2, uint8_t *dst) {
    // Student TODO
    return;
}
#endif

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 *
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 *
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval, extract_regs
 * and decide_alu_op.
 */
comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    // Student TODO
    // basic pass
    out->op = in->op;
    out->print_op = in->print_op;
    out->status = in->status;
    // union pass
    out->multipurpose_val.seq_succ_PC = in->multipurpose_val.seq_succ_PC;
    
    if (out->op == OP_ADRP) {
        out->val_a = in->multipurpose_val.seq_succ_PC - 4;
    }

    // control signals
    d_ctl_sigs_t D_sigs;
    generate_DXMW_control(out->op, &D_sigs, &out->X_sigs, &out->M_sigs, &out->W_sigs);
    
    // alu op
    decide_alu_op(out->op, &out->ALU_op);

    // extract registers
    uint8_t src1 = XZR_NUM;
    uint8_t src2 = XZR_NUM;
    out->dst = XZR_NUM;

    extract_regs(in->insnbits, out->op, in->format, &src1, &src2, &out->dst);
    
    // if stur, read from rt instead of rd
    regfile_read(src1, src2, &out->val_a, &out->val_b);
    
    // immedidate val extract
    extract_immval(in->insnbits, out->op, &out->val_imm);
    
    out->val_hw = bitfield_u32(in->insnbits, 21, 2) * 16; // shift val
    out->cond = bitfield_u32(in->insnbits, 0, 4); //cond for b cond
    return;
}
